---
type: spine

spine:
  # Define variables for all nodes of this type
  defaults:
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # Autonous System Number for BGP
    bgp_as: 65100
  # Define variables per node
  nodes:
    - name: dc1-spine1
      platform: cEOS
      # Node management interface IPv4 address
      mgmt_ip: 172.16.1.11
    - name: dc1-spine2
      platform: cEOS
      # Node management interface IPv4 address
      mgmt_ip: 172.16.1.12

